import { describe, expect, it, vi } from 'vitest'
import { createRepositoryApi } from './repository-api.js'

describe('repository API', () => {
  it('maps foundation, collaboration, review, feedback, and lifecycle operations', async () => {
    const client = { get: vi.fn().mockResolvedValue({}), post: vi.fn().mockResolvedValue({}), patch: vi.fn().mockResolvedValue({}) }
    const api = createRepositoryApi(client)
    await api.createClassProject('task-1', { teamName: 'Team', repositoryName: 'repo' })
    await api.createPersonal({ repositoryName: 'personal' })
    await api.listRepositories({ page: 1, pageSize: 20, status: 'ARCHIVED' })
    await api.getRepository('repo-1')
    await api.updateRepository('repo-1', { expectedUpdatedAt: 'version', description: null })
    await api.readyForReview('repo-1', { expectedUpdatedAt: 'version' })
    await api.requestChanges('repo-1', { expectedUpdatedAt: 'version', feedbackId: 'feedback-1', expectedFeedbackUpdatedAt: 'feedback-version' })
    await api.approveRepository('repo-1', { expectedUpdatedAt: 'version' })
    await api.archiveRepository('repo-1', { expectedUpdatedAt: 'version' })
    await api.restoreRepository('repo-1', { expectedUpdatedAt: 'version' })
    await api.listMembers('repo-1')
    await api.transitionMember('repo-1', 'member-1', { action: 'REMOVE', expectedUpdatedAt: 'member-version' })
    await api.createInvitation('repo-1', { inviteeUserId: 'student-2' })
    await api.listRepositoryInvitations('repo-1')
    await api.listReceivedInvitations()
    await api.acceptInvitation('invite-1')
    await api.declineInvitation('invite-1')
    await api.revokeInvitation('invite-1', { reason: 'Correction' })
    await api.listFeedback('repo-1')
    await api.createFeedbackDraft('repo-1', { feedbackText: 'Review this.' })
    await api.updateFeedbackDraft('feedback-1', { expectedUpdatedAt: 'feedback-version', feedbackText: 'Updated.' })
    expect(client.post).toHaveBeenNthCalledWith(1, '/project-tasks/task-1/repositories', { teamName: 'Team', repositoryName: 'repo' }, undefined)
    expect(client.post).toHaveBeenNthCalledWith(2, '/repositories/personal', { repositoryName: 'personal' }, undefined)
    expect(client.get).toHaveBeenNthCalledWith(1, '/repositories?page=1&pageSize=20&status=ARCHIVED', undefined)
    expect(client.get).toHaveBeenNthCalledWith(2, '/repositories/repo-1', undefined)
    expect(client.patch).toHaveBeenCalledWith('/repositories/repo-1', { expectedUpdatedAt: 'version', description: null }, undefined)
    expect(client.post).toHaveBeenCalledWith('/repositories/repo-1/ready-for-review', { expectedUpdatedAt: 'version' }, undefined)
    expect(client.post).toHaveBeenCalledWith('/repositories/repo-1/request-changes', expect.objectContaining({ feedbackId: 'feedback-1' }), undefined)
    expect(client.post).toHaveBeenCalledWith('/repositories/repo-1/approve', { expectedUpdatedAt: 'version' }, undefined)
    expect(client.post).toHaveBeenCalledWith('/repositories/repo-1/archive', { expectedUpdatedAt: 'version' }, undefined)
    expect(client.post).toHaveBeenCalledWith('/repositories/repo-1/restore', { expectedUpdatedAt: 'version' }, undefined)
    expect(client.get).toHaveBeenCalledWith('/repositories/repo-1/members', undefined)
    expect(client.patch).toHaveBeenCalledWith('/repositories/repo-1/members/member-1', expect.objectContaining({ action: 'REMOVE' }), undefined)
    expect(client.post).toHaveBeenCalledWith('/repositories/repo-1/invitations', { inviteeUserId: 'student-2' }, undefined)
    expect(client.get).toHaveBeenCalledWith('/repositories/repo-1/invitations', undefined)
    expect(client.get).toHaveBeenCalledWith('/repository-invitations', undefined)
    expect(client.post).toHaveBeenCalledWith('/repository-invitations/invite-1/accept', {}, undefined)
    expect(client.post).toHaveBeenCalledWith('/repository-invitations/invite-1/decline', {}, undefined)
    expect(client.post).toHaveBeenCalledWith('/repository-invitations/invite-1/revoke', { reason: 'Correction' }, undefined)
    expect(client.get).toHaveBeenCalledWith('/repositories/repo-1/feedback', undefined)
    expect(client.post).toHaveBeenCalledWith('/repositories/repo-1/feedback-drafts', { feedbackText: 'Review this.' }, undefined)
    expect(client.patch).toHaveBeenCalledWith('/repository-feedback/feedback-1', expect.objectContaining({ feedbackText: 'Updated.' }), undefined)
    expect(api).not.toHaveProperty('issueCredential')
  })
})
